### ISSUE TITLE
ERROR:root:ERROR: not a MATLAB datatype

### ISSUE THREAD

**Issue by hernot** [skjerns/mat7.3#51] opened 2024-02-19 09:25 UTC
I do get error similar to #43 except that it reads `ERROR:root:ERROR: not a MATLAB datatype` (see longer except below). The same files are properly loaded without any error by pymatreader. So They have figured how to read them, so these types likely are new additional non proprietary matlab datatypes or datatypes added by EIDORS Electric Impedance Tomography library.

The exact error is (repeats cut):

```
ERROR:root:ERROR: not a MATLAB datatype: <HDF5 dataset "data": shape (26,), type "<f8">, (float64)
ERROR:root:ERROR: not a MATLAB datatype: <HDF5 dataset "ir": shape (26,), type "<u8">, (uint64)
ERROR:root:ERROR: not a MATLAB datatype: <HDF5 dataset "jc": shape (17,), type "<u8">, (uint64)

/* cut as repeats of the above */

ERROR:root:ERROR: not a MATLAB datatype: <HDF5 dataset "data": shape (2,), type "<f8">, (float64)
ERROR:root:ERROR: not a MATLAB datatype: <HDF5 dataset "ir": shape (2,), type "<u8">, (uint64)
ERROR:root:ERROR: not a MATLAB datatype: <HDF5 dataset "jc": shape (2,), type "<u8">, (uint64)

/* cut as repeats of the above */
```

The exemplary files are
[check_diff.zip](https://github.com/skjerns/mat7.3/files/14328905/check_diff.zip)

With some time at spare, i do not have, I would fork and submit a pull request fixing the up to date unknown data types. For now i do have to fallback to `pymatreader` which is second best alternative for me as neither need mat `< 3.7` support nor `scipy.io.loadmat` backwards compatibility are required.

tested version is latest on PyPi (0.62)
master not tested

**Comment by FelixBenning** [comment] 2024-03-19 14:43
I think the issue is that the check for "MATLAB_sparse" comes too late. In my case the structure is {"A": sparse matrix, ...}
and in `mat2dict` there is a loop `for var in hdf5: ` which then passes the sparse matrix object to `unpack_mat` which then first iterates into it before checking whether it might be MATLAB_sparse.

The solution is, to either not loop in mat2dict, or to put the sparse check at the top level in unpack_mat. I don't understand the rest so I am not sure what should be done

**Comment by skjerns** [comment] 2024-03-23 21:57
should be fixed now!

**Closed by skjerns** 2024-03-23 21:57 UTC
